// <auto-generated />
using System;
using Meetora.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Meetora.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Meetora.Api.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("Meetora.Api.Domain.Entities.MeetingProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("OrganizerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PublicTokenCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("PublicTokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PublicTokenProtected")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerUserId");

                    b.HasIndex("PublicTokenHash")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("meeting_proposals", (string)null);
                });

            modelBuilder.Entity("Meetora.Api.Domain.Entities.MeetingTimeOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MeetingProposalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MeetingProposalId");

                    b.HasIndex("MeetingProposalId", "StartAt", "EndAt")
                        .IsUnique();

                    b.ToTable("meeting_time_options", (string)null);
                });

            modelBuilder.Entity("Meetora.Api.Domain.Entities.TimeOptionVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MeetingProposalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimeOptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uuid");

                    b.Property<string>("VoterName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("MeetingProposalId");

                    b.HasIndex("TimeOptionId");

                    b.HasIndex("MeetingProposalId", "VoterId");

                    b.HasIndex("MeetingProposalId", "VoterId", "TimeOptionId")
                        .IsUnique();

                    b.ToTable("time_option_votes", (string)null);
                });

            modelBuilder.Entity("Meetora.Api.Domain.Entities.MeetingProposal", b =>
                {
                    b.HasOne("Meetora.Api.Domain.Entities.AppUser", "OrganizerUser")
                        .WithMany("MeetingProposals")
                        .HasForeignKey("OrganizerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrganizerUser");
                });

            modelBuilder.Entity("Meetora.Api.Domain.Entities.MeetingTimeOption", b =>
                {
                    b.HasOne("Meetora.Api.Domain.Entities.MeetingProposal", "MeetingProposal")
                        .WithMany("TimeOptions")
                        .HasForeignKey("MeetingProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingProposal");
                });

            modelBuilder.Entity("Meetora.Api.Domain.Entities.TimeOptionVote", b =>
                {
                    b.HasOne("Meetora.Api.Domain.Entities.MeetingProposal", "MeetingProposal")
                        .WithMany()
                        .HasForeignKey("MeetingProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meetora.Api.Domain.Entities.MeetingTimeOption", "TimeOption")
                        .WithMany("Votes")
                        .HasForeignKey("TimeOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingProposal");

                    b.Navigation("TimeOption");
                });

            modelBuilder.Entity("Meetora.Api.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("MeetingProposals");
                });

            modelBuilder.Entity("Meetora.Api.Domain.Entities.MeetingProposal", b =>
                {
                    b.Navigation("TimeOptions");
                });

            modelBuilder.Entity("Meetora.Api.Domain.Entities.MeetingTimeOption", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
